### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by leadalion** [tugstugi/mongolian-speech-recognition#5]
Hi, tugstugi, thanks for sharing your works for speech recognition, while i have some issues about the code:
1. I noticed the vocab is "B абвгдеёжзийклмноөпрстуүфхцчшъыьэюя", why there is a blank behind the character 'B'? I know 'B' stands for blank, but what the ' ' stands for?
2. The convolution operation in this network are all 1-d conv, by this way how can this network learn temporal information?
Look forward to your reply, thank a lot!

**Comment by leadalion** [comment]
I try to understand question2 by myself: 'B' is used to split characters since there are repeated characters, and ' ' is the real blank for printing, am i right?

**Comment by tugstugi** [comment]
1. ' ' is the normal white space. 'B' is the so called 'blank' character used in the CTC loss. You can replace it with any character as long as it doesn't belong to your alphabet of your language and it is the first character  of the 'vocab' variable (both the native PyTorch CTC loss and the warp CTC loss assumes the index of the blank character is 0 that is why it must be the first character).

2. I have implemented [arXiv:1712.09444](https://arxiv.org/abs/1712.09444) and they use only 1-d convolutions. But I think 2D conv will work also, at least for speech commands it works: https://github.com/tugstugi/pytorch-speech-commands
