### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by gumbernator** [tugstugi/mongolian-speech-recognition#6]
eval.py gives Illegal Instruction error.
hardware : AMD A8-6410 APU with AMD Radeon R5 Graphics
![image](https://user-images.githubusercontent.com/44472991/56569961-9780d200-65ec-11e9-8600-1e52b965ebe9.png)

**Comment by tugstugi** [comment]
tested on Colab, it works. So it seems it has to do something with AMD, I don't have an AMD cpu, so I can't debug it.

Here is a Colab notebook for testing: https://colab.research.google.com/drive/1n-dTlBWk6UZZ-QU2GMNmFRyW0IiNLDYh

**Comment by gumbernator** [comment]
Za bayarlalaa.

________________________________
