### ISSUE TITLE
Асуулт

### ISSUE THREAD

**Issue by bayartsogt-ya** [tugstugi/mongolian-speech-recognition#7]
python_speech_features-ын logfbank-ыг яагаад хэрэглэх хэрэгтэйг тайлбарлаж болох уу? (Жишээ нь яагаад mfcc хэрэглээгүй вэ?)
winlen, winstep, preemph зэрэг утгууд нь default хамгийн сайн утга гэж ойлгож болох уу? (Яаж tune хийх ээ сайн ойлгохгүй л байна)

**Comment by tugstugi** [comment]
Одоо бол librosa STFT ашиглаад тэндээ noise mix-дээд тэндээсээ mel spectrogram бодож байгаа. Ер нь бол input нь том тусмаа л сайн. Шууд STFT ашиглах гэхээр томдоод, mfcc дэндүү compressed. Preemphasis ашигласан ч болно ашиглахгүй байсан ч болно, ялгаа байхгүй байсан. Window length болон hop size ч гэсэн сүртэй нөлөө байхгүй. Жишээ нь Mozilla DeepSpeech 512/312 ашиглаж байгаа, энэ репо бол 320/160 (OpenSeq2Seq-тэй ижил). min phoneme length-ээс бага байхад л болох байх. n_fft ч бас сүртэй нөлөө байхгүй, DeepSpeech 2048 ашигладаг, энэ репо 512. Ер нь бол датагаа хэрхэн зөв бэлдэх яаж эвтэйхэн аргадаж сургах л хамгийн чухал байх. Online demo бол жишээ нь 8 сая параметртэй model, DeepSpeech demo-ны model-оос 30 дахин том байх жишээтэй.
