### ISSUE TITLE
Which are the best loss resuls for this project?

### ISSUE THREAD

**Issue by ican24** [tugstugi/mongolian-speech-recognition#8]
Dear Erdene-Ochir Tuguldur,

You are doing great job! I mean also your TTS project.
The codes  are so plain, training is so quick, but at the same time the solutions are powerful and effective.
May I know your best loss resuls for this project?
Recently I had developed Kaldi ASR soluion for my language. 
So I would like to know is it possible to reach near resuls with your Speech Recognition project.

Thank you in advance!

**Comment by tugstugi** [comment]
You can try the `ddp` branch with the `quartznet5x5` model and the native PyTorch CTC loss. This performs currently better than the CRNN model.

**Comment by ican24** [comment]
Thank you!
I have some other (small) questions. May I send them to your email address?
